### ISSUE TITLE
S3 Upload Fails

### ISSUE THREAD

**Issue by jaymell** [quantmind/pulsar-cloud#18]
Using botocore 1.5.14, I encounter the following error trying to upload to s3:

```
Traceback (most recent call last):
  File "async-s3-3.py", line 27, in <module>
    event_loop.run_until_complete(main(event_loop, '/tmp/testfile'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "async-s3-3.py", line 20, in main
    await write_to_s3(loop, f)
  File "async-s3-3.py", line 10, in write_to_s3
    s3 = AsyncioBotocore('s3', 'us-west-2')
  File "/usr/local/lib/python3.5/dist-packages/cloud/aws.py", line 22, in __init__
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloud/asyncbotocore/session.py", line 78, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.5/dist-packages/cloud/asyncbotocore/client.py", line 25, in _get_client_args
    self._response_parser_factory, self._loader)
TypeError: __init__() missing 1 required positional argument: 'exceptions_factory'
```

**Comment by lsbardel** [comment]
Looks like botocore have changed the signature of an internal function.
Do you know the last botocore version >= 1.4.62 working with this package?

**Comment by jaymell** [comment]
It looks like it was working in botocore 1.4.93 and broke in 1.5.0. [This change](https://github.com/boto/botocore/blob/5f3b3a281c61cd301f72044c6d10bbf868b90644/botocore/args.py) 
It would take me some time to familiarize myself with the code, but I can look into submitting a PR for this if helpful.

**Comment by lsbardel** [comment]
This is now fixed and [new release 0.5.5](https://github.com/quantmind/pulsar-cloud/releases/tag/0.5.5) is out.
Thanks for reporting
